name: ARM64 Bridge

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Enter the build branch'
        required: true
        default: 'main'

env:
  PIPENV_PIPFILE: bridges/python/src
  PIPENV_VENV_IN_PROJECT: true
  REPOSITORY_NAME: bella-ios/bella

jobs:
  build:
    name: Build
    permissions:
      packages: write
      contents: write

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.REPOSITORY_NAME }}
          ref: refs/heads/${{ github.event.inputs.branch }}
          token: ${{ secrets.GH_PAT }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
          buildkitd-flags: --config /etc/buildkit/buildkitd.toml
      
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.10
          
      - name: Show Platform
        run: python3 -c "import platform; print(platform.machine())"